### ISSUE TITLE
Fallback to native c-x/c-a.

### ISSUE THREAD

**Issue by aca** [monaqa/dial.nvim#1]
```
3a
```
I can't change 3a to 3b in normal mode at cursor 'a'.
Can we fallback to vim's native \<c-x>/\<c-a>, if there's no match?

Thanks for the plugin.

**Comment by monaqa** [comment]
@aca 
Thanks for reporting the issue!

In the current version `v0.2.0`, there is no fallback to Vim's native commands.
But you can change `3a` to `3b` with dial.nvim's `<C-a>` by adding the following scripts to your `.vimrc`:
```
lua << EOF
local dial = require("dial")

table.insert(dial.config.searchlist.normal, "char#alph#small#str")
EOF
```

**Comment by aca** [comment]
Updated plugin and it works thanks!

**Comment by aca** [comment]
gg
