### ISSUE TITLE
Augends group implementation

### ISSUE THREAD

**Issue by DEliasVCruz** [monaqa/dial.nvim#17]
Based on the documentation, I'm inclined to believe that when you call `require("dial.map").[inc|dec]_normal()` is like calling it passing the `default` group as the argument.

On my understanding this means that you have to specify each augend for each group that you create. Wouldn't it be more intuitive that the default group always gets applied and it's just extended by the named group that is passed as an argument?

Other wise it lends it self for a lot of code duplication if you are a heavy named groups user. Especially if you are defining new augends that you want every group to share.

Please confirm if this is the intended behavior and if there is any plan for change

**Comment by monaqa** [comment]
> Based on the documentation, I'm inclined to believe that when you call require("dial.map").[inc|dec]_normal() is like calling it passing the default group as the argument.

Yes, `require("dial.map").[inc|dec]_normal()` is almost equivalent to`require("dial.map").[inc|dec]_normal("default")`.

> On my understanding this means that you have to specify each augend for each group that you create. Wouldn't it be more intuitive that the default group always gets applied and it's just extended by the named group that is passed as an argument?

Let me confirm about your suggestion. Are you saying, that is, you want to write this statement

```
require("dial.config").augends:register_group{
  default = {
    augend_a,
    augend_b,
    augend_c,
  },
  group_a = {
    augend_a,
    augend_b,
    augend_c,
    augend_d,
  },
  group_b = {
    augend_a,
    augend_b,
    augend_c,
    augend_e,
  },
}
```

this way?

```
require("dial.config").augends:register_group{
  default = {
    augend_a,
    augend_b,
    augend_c,
  },
  group_a = {
    augend_d,
  },
  group_b = {
    augend_e,
  },
}
```

**Comment by monaqa** [comment]
Thanks for the suggestion.
My major concern is that when you want to disable the default augend rule, it will be more complicated than the current way.

The augend of dial.nvim may conflict. For example, a date in "mm/dd/yyyy" format and a date in "dd/mm/yyyy" format will not work well together.
If it is a date format conflict, it may be resolved by the "overwrite" method you propose. But it is also possible for completely different kinds of augend to conflict. For example, an integer with a period delimiter conflicts with a semantic version.

```
1.201.304
```

In such cases, you may want to not only overwrite the augend, but also disable it from the default.

```
require("dial.config").augends:register_group{
  default = {
    augend.integer.new { delimiter = '.' },
  },
  history_md = {
    -- it does not work if the "overwrite" method is adopted.
    augend.semver.alias.semver,
  },
}
```

Taking into account the necessity of disabling augends, I think the current interface is simpler and easier to extend. The user can implement an overwrite-like interface himself/herself, if he/she wants to do.

**Comment by monaqa** [comment]
Closing as there seems to be no other opinions.
