### ISSUE TITLE
Lua map api not working

### ISSUE THREAD

**Issue by DEliasVCruz** [monaqa/dial.nvim#18]
Nvim version:

```sh
NVIM v0.7.0-dev+1258-gbef7552f7
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compilado por runner@fv-az242-546

Features: +acl +iconv +tui
See ":help feature-compile"

     archivo "vimrc" del sistema: "$VIM/sysinit.vim"
            predefinido para $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

Minimal conifg:

- Using packer

```lua
  use { -- Only works for booleans
    "monaqa/dial.nvim",
    config = function()
      local augend = require("dial.augend")
      require("dial.config").augends:register_group{
        -- default augends used when no group name is specified
        default = {
          augend.integer.alias.decimal,   -- nonnegative decimal number (0, 1, 2, 3, ...)
          augend.integer.alias.hex,       -- nonnegative hex number  (0x01, 0x1a1f, etc.)
          augend.date.alias["%Y/%m/%d"],  -- date (2022/02/19, etc.)
        },

        -- augends used when group with name `mygroup` is specified
        mygroup = {
          augend.integer.alias.decimal,
          augend.constant.alias.bool,    -- boolean value (true <-> false)
          augend.date.alias["%m/%d/%Y"], -- date (02/19/2022, etc.)
        }
      }
    end,
  }

-- After plugin setup
vim.api.nvim_set_keymap("n", "<Leader>adf", '<cmd>lua require("dial.map").inc_normal()<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<Leader>adb", '<cmd>lua require("dial.map").dec_normal()<cr>', { noremap = true, silent = true })
```

Expected behaviour:

1. Enter a buffer
2. Type the number `1`
3.  Position cursor over the number 1
4. In normal mode press `<Leader>adf`
5. Get number 2

Actual behaviour:

1. Enter a buffer
2. Type the number `1`
3.  Position cursor over the number 1
4. In normal mode press `<Leader>adf`
5. The number remains unchained

**Comment by monaqa** [comment]
Try mappings as described in the help.

https://github.com/monaqa/dial.nvim/blob/359194d2ed6ab5bebd42958cf89d8dadbf1e016d/doc/dial.txt#L101-L120

```
vim.api.nvim_set_keymap("n", "@adf", require("dial.map").inc_normal(), { noremap = true })
vim.api.nvim_set_keymap("n", "@adb", require("dial.map").dec_normal(), { noremap = true })
```

**Comment by DEliasVCruz** [comment]
It works but, this does not allow for lazy loading of the plugin. Since the call to require is done once the keymap is set. If I want to lazy load only when the `dial` module is load (in a just in time sort of way), It won't work.

Doing this won't work:
`vim.keymap.set("n", "<Leader>adf", function() require("dial.map").inc_normal() end, { noremap = true })`

And calling `:lua require("dial.map").inc_normal()` from the command line won't work either, even without trying to lazy load the plugin

**Comment by monaqa** [comment]
> Doing this won't work:
> `vim.keymap.set("n", "<Leader>adf", function() require("dial.map").inc_normal() end, { noremap = true })`
> 
> And calling `:lua require("dial.map").inc_normal()` from the command line won't work either, even without trying to lazy load the plugin

It's intended. `require("dial.map").inc_normal()` just returns the key sequence to realize the increase/decrease operation, and does not itself cause any side effects on the buffer. Therefore, calling it with the `lua` command will not cause anything to happen.
This specification is designed to achieve flexible dot repeat.

Would lazy loading work well this way?

```
vim.api.nvim_set_keymap("n", "<Leader>adf", "<Plug>(dial-increment)", {})
vim.api.nvim_set_keymap("n", "<Leader>adb", "<Plug>(dial-decrement)", {})
```

**Comment by DEliasVCruz** [comment]
Ok, I made it work lazyly by using this sytax:

```lua
vim.keymap.set("n", "<leader>adf", function()
  return require("dial.map").inc_normal()
end,  { noremap = true, silent = true, expr = true })
```

**Comment by jay-babu** [comment]
This issue should be pinned or on the README.md, many people use lazy loading
