### ISSUE TITLE
Issue with setting up plugin

### ISSUE THREAD

**Issue by AckslD** [monaqa/dial.nvim#3]
I'm just setting up this plugin with the following in my config:
```lua
local opts = {silent = true, noremap=false}
vim.api.nvim_set_keymap('n', '<C-a>', '<Plug>(dial-increment)', opts)
vim.api.nvim_set_keymap('n', '<C-x>', '<Plug>(dial-decrement)', opts)
vim.api.nvim_set_keymap('v', '<C-a>', '<Plug>(dial-increment)', opts)
vim.api.nvim_set_keymap('v', '<C-x>', '<Plug>(dial-decrement)', opts)
vim.api.nvim_set_keymap('v', 'g<C-a>', '<Plug>(dial-increment-additional)', opts)
vim.api.nvim_set_keymap('v', 'g<C-x>', '<Plug>(dial-decrement-additional)', opts)
```
However for example if I do `<C-x>` on `2021-03-22` then with my cursor on the first character I just get `2020-03-22` instead of `2021-03-21` which is what I would have expected.

If I understood it correctly it should work by default on dates right? Or do I need to add that to the searchlist?

**Comment by monaqa** [comment]
@AckslD 
It reproduced, and turned out to be a bug caused by a mistake in the pattern description.

Please update this plugin and check if the problem has been solved.
If you are still having problems, feel free to reopen this issue or create a new issue.

Thank you for your report!

**Comment by AckslD** [comment]
Thanks for the quick response @monaqa! I updated to the latest version but for some reason I still have the same behaviour.

**Comment by monaqa** [comment]
@AckslD 
Do you have the cursor on `2021` when you press `<C-x>`?
If so, the year of `2021-03-22` is decremented, resulting in `2020-03-22`.
To decrement the date, you need to bring the cursor on the string `22` or before the string `2021-03-22`.

**Comment by AckslD** [comment]
@monaqa Sorry my bad, that makes a lot of sense and it does indeed work :) Thanks for the help!
