### ISSUE TITLE
Enhancement: Add case-insensitive cycling

### ISSUE THREAD

**Issue by maxmahlke** [monaqa/dial.nvim#31]
I recently discovered this plugin and I'm really fond of the extension of the `c-a` and `c-x` functionality, it's a great idea!

One feature I miss in the definition of the custom cycling groups is to have case-insensitive cycling, e.g.

```
augend.constant.new({
	elements = { "left", "right" },
	word = true,
	cyclic = true,
        case_sensitive = false,
})
````

could be used to turn `left` into `right` and `Left` into `Right`. A more common use case is the `true`/`false` tuple, which in some languages like `python` is `True`/`False`.

**Comment by monaqa** [comment]
Thank you for the suggestion.
We added `preserve_case` option, which enables case-preserved cycling, such as
* `true -> false -> true -> ...`
* `True -> False -> True -> ...`
* `TRUE -> FALSE -> TRUE -> ...`
Feel free to reopen this issue if you have any problem about this feature.

**Comment by maxmahlke** [comment]
Just tested it, it works perfectly! Thanks for the quick response.
