### ISSUE TITLE
[Feature Request] Option to only inc/dec when augend is under cursor

### ISSUE THREAD

**Issue by aMOPel** [monaqa/dial.nvim#36]
#### Problem:

Right now I have this in my config:
```
        augend.constant.new { elements = { 'on', 'off' }, word = false, cyclic = true, },
```

I have `word = false`, since I wanna allow for cases where 'on'/'off' is part of an identifier like 'turn_on` etc.

Now the problem with that is, that I get a ton of false positives when I wanna increment something else in the line. I use `<c-a>` and it jumps to an occurrence of "on" as part of another word since those 2 letters appear everywhere in the English language apparently.

So then I turned "on" to "off" unintentionally in some word and have to decrement again, to finally jump to the actual place I where wanted to increment something.

#### Solution:

An option in the augends, that allows to turn off the jumping/seeking for this particular augend, would be great. Eg:
```
        augend.constant.new { elements = { 'on', 'off' }, word = false, cyclic = true, jumpTo = false},
```
In that case, the increment would only work, if it matches something right under the cursor.

**Comment by monaqa** [comment]
I will consider the turn off feature, but first let me ask about the false positive problem.

What you want to do is to toggle `.*_on` identifier and `.*_off` identifier?
If so, this can be done with the following configuration without the risk of false positives.

```lua
require("dial.config").augends:register_group {
    default = {
        -- matches identifiers which end with "_on" and "_off"
        augend.constant.new {
            elements = {"on", "off"},
            pattern_regexp = [[\V_\zs\(%s\)\>]],
        },
        -- matches "on" and "off" as single word
        augend.constant.new {
            elements = {"on", "off"},
            word = true,
        },
    },
}
```

**Comment by aMOPel** [comment]
Alright. Interesting.

Didn't read deep enough into the readme to come up with that solution apparently.

It wasn't just about this very specific snake_case but more generally about "on"/"off" appearing in an identifier. Also when there is text following and for eg. camelCase.

In that same notion an option for case insensitivity of the elements would be nice. I think I've seen a related issue already.

Of course I could adapt the regex to fit my needs. Still I believe the option to turn off the jumping, in general, and for specific augends, would make the plugin more adaptable to user needs.

**Comment by monaqa** [comment]
> In that case, the increment would only work, if it matches something right under the cursor.

In fact, you can achieve this functionality with a little advanced configuration. Please try this:

```lua
local augend_onoff = augend.constant.new {
    elements = { "on", "off" },
    word = false,
    cyclic = true,
    preserve_case = true,
}

require("dial.config").augends:register_group {
    default = {
        augend.user.new {
            find = function (line, cursor)
                local range = augend_onoff:find(line, cursor)
                if range ~= nil then
                    if range.from <= cursor and cursor <= range.to then
                        return range
                    end
                end
                return nil
            end,
            add = function (text, addend, cursor)
                return augend_onoff:add(text, addend, cursor)
            end
        }
    },
}
```

> In that same notion an option for case insensitivity of the elements would be nice. I think I've seen a related issue already.

Yes, conversion with preserving case has been already supported. The option`preserve_case` does.

**Comment by aMOPel** [comment]
Thank you :)
Props to your API design.

I still think adding the flag to the augend config table would be nice, but obviously you gotta judge that for yourself.

**Comment by aMOPel** [comment]
This isn't really worth a new issue, I just wanted to mention that the option `preserve_case` has a very counter intuitive name.
What it effectively does if it's true, is to make the string's case insensitive, right? So `ignore_case` would be a much more fitting and commonly used name for such an option. Or maybe it's just me getting confused by this^^

**Comment by monaqa** [comment]
Augend with `preserve_case = true` attempts to preserve the case during conversion.

> * All lowercase (e.g.: `true <-> false`)
> * All uppercase (g.g.: `TRUE <-> FALSE`)
> * Only the first letter is uppercase (e.g.: `True <-> False`)

The name `ignore_case` does not express this property.

**Comment by monaqa** [comment]
For a better name, I think "try_preserve_case" would be appropriate.
