### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by axieax** [monaqa/dial.nvim#37]
Hi, I've encountered two issues from the recent release:

1. `augend.paren.alias.lua_str_literal` doesn't seem to include the single quote character
2. Quote and bracket priority doesn't seem to be respected (e.g. `("")` with cursor on first quote will target brackets instead of quote).

**Comment by monaqa** [comment]
Thank you for the reporting.

As for 1., #38 will solve the problem (thank you @gegoune !).

As for 2., it is intended behavior. Please refer the comment: https://github.com/monaqa/dial.nvim/issues/14#issuecomment-1065861000

**Comment by axieax** [comment]
For 1, dial seems to prefer `augend.paren.alias.quote` over `augend.paren.alias.lua_str_literal`. Is it possible to limit by filetype (maybe a conditional check).

**Comment by monaqa** [comment]
Possible.
Please try the following settings:

```lua
require("dial.config").augends:register_group {
    default = {
        augend.paren.alias.quote,
    },
    in_lua = {
        augend.paren.alias.lua_str_literal,
    },
}

vim.keymap.set("n", "<C-a>", require("dial.map").inc_normal())
vim.keymap.set("n", "<C-x>", require("dial.map").dec_normal())
vim.keymap.set("v", "<C-a>", require("dial.map").inc_visual())
vim.keymap.set("v", "<C-x>", require("dial.map").dec_visual())
vim.keymap.set("v", "g<C-a>", require("dial.map").inc_gvisual())
vim.keymap.set("v", "g<C-x>", require("dial.map").dec_gvisual())

vim.api.nvim_create_autocmd("FileType", {
    pattern = "lua",
    callback = function ()
        vim.keymap.set("n", "<C-a>", require("dial.map").inc_normal("in_lua"), {buffer = true})
        vim.keymap.set("n", "<C-x>", require("dial.map").dec_normal("in_lua"), {buffer = true})
        vim.keymap.set("v", "<C-a>", require("dial.map").inc_visual("in_lua"), {buffer = true})
        vim.keymap.set("v", "<C-x>", require("dial.map").dec_visual("in_lua"), {buffer = true})
        vim.keymap.set("v", "g<C-a>", require("dial.map").inc_gvisual("in_lua"), {buffer = true})
        vim.keymap.set("v", "g<C-x>", require("dial.map").dec_gvisual("in_lua"), {buffer = true})
    end
})
```

**Comment by axieax** [comment]
Would this mean I'd have to duplicate all my other default mappings to the `in_lua` group as well? Surely there's a better way to do this (e.g. a custom or built-in function which chooses `lua_str_literal` instead of the normal `quote` when the current filetype is lua).
