### ISSUE TITLE
How to add custom formats

### ISSUE THREAD

**Issue by cloggier** [monaqa/dial.nvim#4]
I would love to add day of a week and months increments/decrements. How to do that?

**Comment by monaqa** [comment]
Thanks for the question. I am actually planning to describe how to define custom rules (called "augend" in dial.nvim) sometime, but I have not done it yet.

To create your own augend (increment/decrement rule), follow the three steps:

1. create a table with three fields: `desc`, `find`, and `add`.

  - `desc` is a text field that explains how the rule works.
  - `find` represents a function that detects a specific pattern from a string in a buffer.
  - `add` represents a function that actually performs addition to the detected string.

2. register the table to `require("dial").augends` with any name you like.

3. set the name to `dial.config.searchlist.normal`.

Here is the example. The code below defines a new rule for increasing/decreasing a date written in the format `mm/dd/yyyy`.

```lua:init.lua
local dial = require("dial")

local my_date_format = {
    desc = "standard date mm/dd/yyyy",

    find = dial.common.find_pattern("%d%d/%d%d/%d%d%d%d"),

    add = function(cursor, text, addend)
        local month = tonumber(text:sub(1, 2))
        local day = tonumber(text:sub(4, 5))
        local year = tonumber(text:sub(7, 10))
        if cursor == nil then cursor = 5 end  -- default: day
        if cursor >= 1 and cursor <= 2 then
            month = month + addend
            cursor = 2
        elseif cursor >= 6 and cursor <= 10 then
            year = year + addend
            cursor = 10
        else
            day = day + addend
            cursor = 5
        end
        local date = os.time{year=year, month=month, day=day}
        text = os.date("%m/%d/%Y", date)
        return cursor, text
    end
}

dial.augends["custom#my_cool_date"] = my_date_format

dial.config.searchlist.normal = {
    "custom#my_cool_date"
}
```

Perhaps [this code](https://github.com/monaqa/dial.nvim/blob/3390a2b304c7c8d22f15797aaca34b6bb3b39c73/lua/dial/augends.lua) can help you with the implementation.

**Comment by cloggier** [comment]
@monaqa thanks for the example. I can see more or less how is that suppose to work, but am not sure how to add and extract from `%A` date formatted string.
