### ISSUE TITLE
Date  decreasing issue 

### ISSUE THREAD

**Issue by leiserfg** [monaqa/dial.nvim#49]
I'm using the most simple config possible, the mappings and a single augend 

```lua
augend.date.alias["%Y-%m-%d"]
``` 
It works fine for most dates, but for some like `2022-10-30` and `2022-09-30`, it does not decrease (I'm calling it with the cursor over the day).

**Comment by leiserfg** [comment]
The issue is reproducible with this small test:

```lua
local date = require("dial.augend").date
local augend = date.alias["%Y-%m-%d"]
augend.kind = "day"
vim.pretty_print(augend:add("2022-10-30", -1))
```

**Comment by monaqa** [comment]
Thanks for the report, but I could not reproduce it in my environment.
 `vim.pretty_print(augend:add("2022-10-30", -1))` outputs
```
{
  cursor = 10,
  text = "2022-10-29"
}
```
and this is as expected (ditto for the other two examples). Are you using the latest version (https://github.com/monaqa/dial.nvim/commit/61afb28f61ba090a67a88186f7bc8a94212e509a)?

**Comment by leiserfg** [comment]
I was, right now I'm already in bed, will have a look at it tomorrow morning. (Writing from Europe)

**Comment by leiserfg** [comment]
I just tried again and now it works fine (without updating or touching anything else) I'm thinking it has to do with the hour I was testing it (near 12pm) and the fact that you internally are using `os.date` .

**Comment by leiserfg** [comment]
I think that's the issue, here https://github.com/monaqa/dial.nvim/blob/master/lua/dial/augend/date.lua#L429 you are using the current time as the seed of the calculations which means the code can behave differently depending on when it's executed, I think it's safer to use a fixed (well known) value.
