### ISSUE TITLE
Wrong date format

### ISSUE THREAD

**Issue by gegoune** [monaqa/dial.nvim#5]
Hi, got a date in `DD/MM/YY` format, but dial treats it as if it was `MM/DD/YY`, so first field I can only increment to 12, while incrementing middle one past 30-31 (depending on month) bumps first field by one.

I am not seeing `MM/DD/YY` format in readme, not sure where it's coming from. How can I disable that date format altogether?

**Comment by monaqa** [comment]
If the augend `date#[%m/%d]` is enabled, this augend will match the "01/03" part of "01/03/2021", regarding the substring as January 3rd.
Could you disable `date#[%m/%d]` and try it?
If it still does not work, please show me the minimal reproducible `init.vim` / `init.lua`.

Thanks!

**Comment by cloggier** [comment]
OK, so it works, thanks. Used 
```lua
table.remove(dial.config.searchlist.normal, 5) -- remove "date#[%m/%d]" augend
```
Do you think there is better way of doing this? Feels bit flaky, as it might disable something else at some point in future.

Also, I noticed now that there is no default augends for most common date format "MM/DD/{YY}YY". Would you consider adding them to your plugin or insist on users adding them themselves? According to [Wikipedia](https://en.wikipedia.org/wiki/Date_format_by_country) MDY is only used in handful of countries while rest of the planet uses DMY (and YMD).

**Comment by monaqa** [comment]
You can also simply list the search target augends:
```lua
dial.config.searchlist.normal = {
    "number#decimal",
    "number#hex",
    "date#[%Y/%m/%d]",
    "date#[%H:%M]"
}
```
In this way, you don't have to worry about invalidating some unintended augends.

> Also, I noticed now that there is no default augends for most common date format "MM/DD/{YY}YY". Would you consider adding them to your plugin or insist on users adding them themselves? According to Wikipedia MDY is only used in handful of countries while rest of the planet uses DMY (and YMD).

Hmm, that's right, it would be better to provide the globally used date format in the plugin.
Okay, I will try to add some augends with new date format, such as `date#[%d/%m/%Y]` or `date#[%m/%d/%Y]` (in fact, it is not hard to implement them).
