### ISSUE TITLE
lazy.nvim: Failed to run config for dial.nvim: module 'dial' not found

### ISSUE THREAD

**Issue by ADkun** [monaqa/dial.nvim#63]
Here's my lazy.nvim configuration of dial.nvim

```lua
{
    "monaqa/dial.nvim",
    lazy = true,
    event = "User FileOpened",
    config = function()
        local dial = require("dial")
        -- ...
    end
}
```

**Comment by monaqa** [comment]
Perhaps dial.nvim is not the issue and you should ask for help from lazy.nvim.

**Comment by monaqa** [comment]
I guess what you say `User FileOpened` refers to what is defined in [LunarVim](https://github.com/LunarVim/LunarVim).

https://github.com/LunarVim/LunarVim/blob/23a16d93306310358efb882c4193a0fabcbda5e1/lua/lvim/core/autocmds.lua#L145

Please report it to LunarVim, as it is probably a LunarVim issue.
