### ISSUE TITLE
Increment/decrement on fooBar1 while cursor is over the 1

### ISSUE THREAD

**Issue by sbeyer** [monaqa/dial.nvim#69]
Description: The increment/decrement operation is performed on the whole word. In case the word contains a number AND the cursor is on that number, I would expect that the operation is only performed on the respective number, not on the whole word before the number.

Situation to reproduce:
* used plugin configuration: https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/editing-support/dial-nvim/dial-nvim.lua
* type `fooBar1` in insert mode and press escape (cursor is over 1)
* press `<C-x>` (which is mapped to `dec_normal()`).

Expected result:
* `fooBar0`

Actual result:
* `FOO_BAR1`

Note that it works as expected for words that are only lower-cased letters, e.g. `word1` becomes `word0`.

I am not sure if you will regard it as a real issue or if it's a wontfix situation. The main issue with this issue is that I can't use `<C-a>`/`<C-x>` anymore as without the plugin. My workaround will probably be to map dial's functionality to `<leader><C-a>` and `<leader><C-x>`.

**Comment by monaqa** [comment]
In this situation, both of `augend.integer.alias.decimal` (converts between `FOO_BAR1` <--> `fooBar1`) and `augend.case.new` (`0` <--> `1`) are set as the default augends. Since dial.nvim prefers the wider range when finding targets for increment/decrement, in this setting you cannot make `fooBar1` into `fooBar0`.

The workaround you can take now is, as you say, to make it a separate mapping.
In my opinion, the easiest way is probably to make just the case conversion a separate mapping, like `gc`:

```lua
  keys = {
    ...,
    -- add the case conversion mapping
    {
      "gc",
      function()
        require("dial.map").manipulate("increment", "normal", "case")  -- select the "case" group
      end,
      desc = "Convert case",
    },
  },
  config = function()
    local augend = require "dial.augend"
    require("dial.config").augends:register_group {
      default = {
        augend.integer.alias.decimal,
        augend.integer.alias.hex,
        augend.date.alias["%Y/%m/%d"],
        augend.constant.alias.bool,
        augend.semver.alias.semver,
      },
      -- define a group named "case", which only converts the case and not increment/decrement numbers.
      case = {
        augend.case.new {
          types = { "camelCase", "PascalCase", "snake_case", "SCREAMING_SNAKE_CASE" },
        },
      },
    }
  end,
```

**Comment by sbeyer** [comment]
Sorry, I forgot to reply. I am currently going with a separate mapping and it's quite fine. Thanks for considering and your alternative approach.
