### ISSUE TITLE
Keeping cursor in place 

### ISSUE THREAD

**Issue by premell** [monaqa/dial.nvim#7]
Often you just want to change something quick in the middle of the line without actually doing something else there. 90% of the time I use dial I find myself just jumping back to my starting position after my cursor moves to the thing I want to increment. The best thing about dial is that I dont have to go to the number in order to change it, so it feels unessesary to jump there anyway. It would be nice to have an option to keep the cursor in place while incrementing the target.

**Comment by monaqa** [comment]
As a simple and ad-hoc solution, you can avoid moving the cursor by the following mapping:

```
nmap <expr> <C-a> 'm`' .. v:count1 .. '<Plug>(dial-increment)``' 
nmap <expr> <C-x> 'm`' .. v:count1 .. '<Plug>(dial-decrement)``' 
```

**Comment by monaqa** [comment]
The above settings should solve the problem. Closed.

**Comment by pocreagan** [comment]
Here's a version which doesn't use a mark (I remap "m").

```lua
local dial_inc_keep_cursor_pos = function()
  local pos = vim.api.nvim_win_get_cursor(0)
  local cmd = require('dial.map').inc_normal()
  local keys = vim.api.nvim_replace_termcodes(cmd, true, true, true)
  vim.api.nvim_feedkeys(keys, 'm', false)
  vim.schedule(function()
    vim.api.nvim_win_set_cursor(0, pos)
  end)
end
```

Killer plugin, thanks.
