### ISSUE TITLE
Powerful alternatives

### ISSUE THREAD

**Issue by hinell** [monaqa/dial.nvim#80]
Hi. I suggset you list powerful alternatives:
* [nvim-treesitter#incremental-selection](https://github.com/nvim-treesitter/nvim-treesitter#incremental-selection)
* [hinell/crazy-node-movement](https://github.com/hinell/crazy-node-movement/tree/master) - fork with improvements

**Comment by monaqa** [comment]
The two plugins don't seem to have anything in common with dial.nvim, in what ways are they alternatives?

**Comment by hinell** [comment]
@monaqa Sorry, Wrong repo. Please, delete issue.

**Comment by hinell** [comment]
@monaqa Sorry, Wrong repo. Please, delete the issue.
