### ISSUE TITLE
[question] difference between `gnormal` and `normal`

### ISSUE THREAD

**Issue by tummetott** [monaqa/dial.nvim#81]
Hello, 

thank you for this awesome plugin. I have one question:

Whats the difference between:

```lua
require("dial.map").manipulate("increment", "gnormal") 

-- and

require("dial.map").manipulate("increment", "normal")
```

I unserstand `gvisual` can increment the block:

```
1
1
1
``` 

to 

```
1
2
3
```
but whats the purpose of the `g` prefix in normal mode?

Thank you

**Comment by monaqa** [comment]
`g<C-a>` is a feature to create sequential numbers located far apart.
Almost the same as `<C-a>`, but different when dot repeat is performed.

For instance:

```python
def test_foo_0():
    assert 100 + 100 == 200

def test_foo_0():
    assert 100 + 100 == 200

def test_foo_0():
    assert 100 + 100 == 200
```

By executing `/def<CR>g<C-a>n.n.`, the buffer is edited as follows:

```python
def test_foo_1():
    assert 100 + 100 == 200

def test_foo_2():
    assert 100 + 100 == 200

def test_foo_3():
    assert 100 + 100 == 200
```

Please refer to `:h dial-additive-dot-repeating`.

**Comment by tummetott** [comment]
Thank you for the clarification
