### ISSUE TITLE
How to increase all the numbers in the line

### ISSUE THREAD

**Issue by Demianeen** [monaqa/dial.nvim#86]
Let's assume I have a list like this:
fn - 1 : yabai -m space --focus 1
fn - 1 : yabai -m space --focus 1
fn - 1 : yabai -m space --focus 1
fn - 1 : yabai -m space --focus 1
fn - 1 : yabai -m space --focus 1
fn - 1 : yabai -m space --focus 1
fn - 1 : yabai -m space --focus 1
fn - 1 : yabai -m space --focus 1

I would like to increase both, the first 1 and the second 1 in the same line. But when I do g <C-a> it increases the first 1. Is it possible to increase both numbers?

**Comment by monaqa** [comment]
There is currently no generic way to accomplish this in a single text edit.
But using `g<C-a>` in block visual mode, this can be accomplished with two text edits.
Simply select first 1 and execute `g<C-a>`, then select second 1 and execute `g<C-a>` (or dot repeat can also be used in this case).

**Comment by Demianeen** [comment]
Oh, my, that's works! Thank you)
