### ISSUE TITLE
The order of elements 

### ISSUE THREAD

**Issue by NickyMeuleman** [monaqa/dial.nvim#87]
This was something that confused me for a bit, but the order of elements is important.
I'd like the strings I defined in elements to all be matched before an inc/decrement takes place.
Right now, it finds the first match and applies that.

Example that's much clearer:
I wanted a toggle between `<`, `<=`, `>`, and `>=`
```lua
local non_word_pattern = "\\C\\M\\(%s\\)"
augend.constant.new({
  elements = { "<", "<=", ">", ">=" },
  pattern_regexp = non_word_pattern,
}),
```

However, with this:
1. original: `1 <= 2`
1. incremented:`1 <== 2` 

I would like the result to be `1 > 2`

What I first though:

This is because the `<` in `<=` is detected and the element next to `<` is `<=`, resulting in an extra `=`.

My workaround for now is to order the elements in such a way that this can not happen, the different order is a minor annoyance
```lua
augend.constant.new({
  elements = { "<=", ">=", "<", ">" },
  pattern_regexp = non_word_pattern,
}),
```

What I think now:

I have to tweak the `pattern_regexp` somehow, but I don't know enough regex to get it to behave the way I want.

So my question is: How can I change this behaviour, and can the current behaviour be documented please?
(If it already is, I apologize, I missed it)

**Comment by monaqa** [comment]
Although `augend.constant` is simple to configure, it cannot express complex detection logic.
However, in this case, there is a configuration solution without modifying dial.nvim:

```lua
augend.constant.new {
    elements = { "<", "<=", ">", ">=" },
    pattern_regexp = [[\C\M\(%s\)=\@!]],
},
```

Adding the regular expression `=\@! ` to regexp to match `<=` instead of `<` given `1 <= 2`.
At the cost of not matching strings like `<==`, but this is not a disadvantage in this case.

**Comment by NickyMeuleman** [comment]
Awesome, thank you!
This prompted me to learn more about vim's regex syntax.
