### ISSUE TITLE
When i wanna create many custom augends, it there a way to avoid writing `table.insert...` over and over again?

### ISSUE THREAD

**Issue by AstroShen** [monaqa/dial.nvim#9]
dial.augends["custom#boolean"] = dial.common.enum_cyclic{ strlist = {"true", "false"} }
dial.augends["custom#direction"] = dial.common.enum_cyclic{ strlist = {"North", "South", "West", "East"} }
dial.augends["custom#great"] = dial.common.enum_cyclic{ strlist = {">", "<"} }
dial.augends["custom#greatequal"] = dial.common.enum_cyclic{ strlist = {">=", "<="} }
dial.augends["custom#selfadd"] = dial.common.enum_cyclic{ strlist = {"++", "--"} }
table.insert(dial.config.searchlist.normal, "custom#boolean")
....
....
....

**Comment by monaqa** [comment]
There are two steps you need to take to add a custom augend:

1. register the augends you want to add in `dial.augends`.
2. list the augends you want to enable in `dial.config.searchlist.normal` / `dial.config.searchlist.visual`.

For example, you can do the following

```
dial.config.searchlist.normal = { "custom#boolean", "custom#direction" }
```

(but the default augends will not work in this case).

**Comment by AstroShen** [comment]
It is a little trouble. But i think the plugin you devepled is very general and can be the best Ctrl-A/X plugin. Hope the more extensible way of custom augends.

**Comment by AstroShen** [comment]
BTW, suggest support none-word character custom augends like "++, --", ">=, <=", ....

**Comment by axieax** [comment]
@AstroShen you can use `vim.list_extend` to avoid repeated `table.insert` calls, as below:

```lua
local dial = require("dial")

local extra_augends = {
	"markup#markdown#header",
	"date#[%H:%M:%S]",
}

local custom_augends = {
	boolean = dial.common.enum_cyclic({ strlist = { "true", "false" } }),
	Boolean = dial.common.enum_cyclic({ strlist = { "True", "False" } }),
	-- on = dial.common.enum_cyclic({ strlist = { "on", "off" } }),
	-- ON = dial.common.enum_cyclic({ strlist = { "ON", "OFF" } }),
	-- On = dial.common.enum_cyclic({ strlist = { "On", "Off" } }),
	-- direction = dial.common.enum_cyclic({ strlist = { "north", "south", "west", "east" } }),
	-- Direction = dial.common.enum_cyclic({ strlist = { "North", "South", "West", "East" } }),
	greater = dial.common.enum_cyclic({ strlist = { ">", "<" } }),
	-- equal = dial.common.enum_cyclic({ strlist = { "==", "!=" } }),
	-- Equal = dial.common.enum_cyclic({ strlist = { "===", "!==" } }),
	-- greaterEqual = dial.common.enum_cyclic({ strlist = { ">=", "<=" } }),
	-- selfAdd = dial.common.enum_cyclic({ strlist = { "++", "--" } }),
}

-- register custom augends
for k, v in pairs(custom_augends) do
	local augend_name = "custom#" .. k
	dial.augends[augend_name] = v
	table.insert(extra_augends, augend_name)
end

-- extend capabilities
vim.list_extend(dial.config.searchlist.normal, extra_augends)
vim.list_extend(dial.config.searchlist.visual, extra_augends)
```

Unfortunately for me, my "greater", "equal", "Equal", "greaterEqual", "selfAdd" custom augments aren't working as expected, not sure why though..

For example:
`1 < 2` with cursor on `<` will move the cursor to `2` and increment that number to `3`, but `a < b` with cursor on `<` will do nothing.

I'm on nvim v0.6.1. Btw +1 for AstroShen's suggestion for supporting these extra augends as well :)

**Comment by monaqa** [comment]
@AstroShen @axieax I am sorry for late response, and thank you for your suggestions!

Recently, I've been fascinated by [denops.vim](https://github.com/vim-denops/denops.vim), which can create plugins using TypeScript, and [dps-dial.vim](https://github.com/monaqa/dps-dial.vim) is a product of that. dps-dial.vim supports dot-repeat and is very versatile, but it requires [Deno](https://deno.land) runtime to be installed.
To be honest, I am undecided which one I should focus on, dial.nvim or dps-dial.vim, because both of them have their advantages.

By the way, you can add non-word augends like this:
```
local custom_augends = {
  greater = dial.common.enum_cyclic({ strlist = { ">", "<" }, ptn_format = "\\C\\M\\(%s\\)" }),
}
```

**Comment by axieax** [comment]
Interesting I see now! Is the functionality similar for both versions, other than dot-repeat and case switching (this sounds so cool!)? I'm curious as to what advantages each have over the other (definitely compatibility for Lua, speed and development should still be quite good as well tho?).

Thanks for the non-word augends guide btw! Most of them work now, except for the self increment ones (+=, ++) for some reason. This is what I'm currently using:
```lua
local non_word_pattern = "\\C\\M\\(%s\\)"
local custom_augends = {
  selfIncrementBy = dial.common.enum_cyclic({
    strlist = { "+=", "-=", "*=", "/=", "//=", "%=" },
    ptn_format = non_word_pattern,
  }),
  selfIncrementOne = dial.common.enum_cyclic({ strlist = { "++", "--" }, ptn_format = non_word_pattern }),
}
```

**Comment by monaqa** [comment]
Thank you, there was a bug that some characters (such as `+`, `.`) was treated as special characters of Lua.
I fixed it and now (https://github.com/monaqa/dial.nvim/commit/3b70b2a6ce7d44826420f3653feef23501767577) the following config should work as expected. 

```
local non_word_pattern = "\\C\\M\\(%s\\)"
local custom_augends = {
  selfIncrementBy = dial.common.enum_cyclic({
    strlist = { "+=", "-=", "*=", "/=", "//=", "%=" },
    ptn_format = non_word_pattern,
  }),
  selfIncrementOne = dial.common.enum_cyclic({ strlist = { "++", "--" }, ptn_format = non_word_pattern }),
}
```

And I decided to reimplement the functionality of dps-dial in Lua and release it as a new version of dial.nvim.
I will update dial.nvim soon to support new features such as dot-repeat.

**Comment by axieax** [comment]
Ahh this explains the bugged behaviour! Thanks for the fix :)
Looking forward to the new version!!

**Comment by monaqa** [comment]
A new version has been released with a completely new configuration interface. So this issue is now closed.
If you have any problems with the new interface, please open a new issue.
