### ISSUE TITLE
How to cycle between elements that has dot in it?

### ISSUE THREAD

**Issue by tuephan-hi** [monaqa/dial.nvim#91]
I have this config that is kind of working but I'm not fully satisfied with it since it's kinda hacky:

```
return {
  "monaqa/dial.nvim",
  opts = function(_, opts)
    local augend = require("dial.augend")
    vim.list_extend(opts.groups.typescript, {
      augend.constant.new({
        elements = { "it", "it.only" },
        word = false,
        cyclic = true,
        pattern_regexp = [[\C\V\<\(%s\)\(\.only\)\?\>]], -- Custom pattern to match 'it' and 'it.only'
      }),
    })
  end,
}
```

Also I want to match the element only when it's starting of the line. I have been trying to add the `\^` in various places in the `pattern_regexp` but no success so far. Appreciated if anyone has a way to make it work. Thank you!

**Comment by monaqa** [comment]
> Also I want to match the element only when it's starting of the line.

Complex conditions for target string cannot be handled with `augend.constant`. Use `augend.user` instead, for instance:


```lua
augend.user.new {
    find = function(line, cursor)
        local s, e = vim.regex([[\v^\s*\zsit(.with)?]]):match_str(line)
        if s ~= nil then
            return { from = s + 1, to = e }
        end
    end,
    add = function(text, addend, cursor)
        if text == "it" then
            text = "it.with"
        else
            text = "it"
        end
        return { text = text }
    end,
},
```

**Comment by tuephan-hi** [comment]
Thanks for the quick response. It seems to work as expected with this custom `augent.user`!
