### ISSUE TITLE
ON/OFF

### ISSUE THREAD

**Issue by bennypowers** [monaqa/dial.nvim#92]
Thank you for publishing this useful package

CMakeLists.txt files can set boolean options with the `ON`/`OFF` keywords. take this example from the [input-leap](https://github.com/input-leap/input-leap) package:

```cmake
option(INPUTLEAP_BUILD_GUI "Build the GUI" ON)
option(INPUTLEAP_BUILD_INSTALLER "Build the installer" ON)
option(INPUTLEAP_BUILD_TESTS "Build the tests" ON)
option(INPUTLEAP_USE_EXTERNAL_GTEST "Use external installation of Google Test framework" OFF)
option(INPUTLEAP_BUILD_X11 "Build with XWindows support" ON)
option(INPUTLEAP_BUILD_LIBEI "Build with libei support" ON)
option(INPUTLEAP_DEPLOY_FLATPAK_SCRIPT "Deploy Flatpak script [Experimental]" OFF)
```

dial.nvim provides enough extensibility for users to add their own configuration to toggle `On`/`Off`. This issue is to request that `ON` and `OFF` be configured by default as aliases for bool `true`/`false`.

Thank you for considering this issue.

**Comment by monaqa** [comment]
Thank you for the suggestion.

I think "on" and "off" is too generic words to introduce as a default.
Introducing some new augends to default set may increase some convenience, but it also increases the risk of incrementing/decrementing unintended text.

For example, given the line `meeting on 21 July` and the cursor on the first `m`, what would a user expect to press `<C-a>`?
The user expects `meeting on 22 July`, I guess, not `meeting off 21 July`.

Usage like the example you gave should only be enabled for specific filetypes. It should be set by the user.
